// * This Java source file was generated by the Gradle 'init' task.
package basiclibrary;

import java.util.Random;

public class Library {


    public static void main (String []args){

//        roll(4);
//        boolean b = containsDuplicates( new int[]{1,2,3,4,6,9});
//
//      float a=  CalculatingAverages(new int[]{1,1,1,1});
//        int[][] weeklyMonthTemperatures = {
//                {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}
//        };
//        float c =ArraysOfArrays(weeklyMonthTemperatures);
//        System.out.println(c);
    }
public  int [] roll(int num){
    Random dice = new Random();
    int [] arr =new int[num];

    for (int index=0;index<num ;index++){
        int prop = dice.nextInt(6) +1;
        arr[index]=prop;

    }
    return arr;
}

public  boolean containsDuplicates(int[]arr){
     for (int index=0;index<arr.length;index++){
         int num=arr[index];
         for (int index2=0;index2<arr.length;index2++){
            if (arr[index2]==num && index!=index2){
                return true;
            }
         }
     }
        return false;
}

public  float CalculatingAverages(int[]arr){
        int sum =0;
        for (int index=0;index<arr.length;index++){
            sum+=arr[index];
        }
        return sum/ arr.length;
}

public  float ArraysOfArrays(int[][]arr){
        int sum=0;
        int count =0;
        for (int index =0;index<arr.length;index++){
            for (int index2=0;index2< arr[index].length;index2++){
                sum+=arr[index][index2];
                count++;
            }
        }
        return sum/count;
}



}
