// * This Java source file was generated by the Gradle 'init' task.
package basiclibrary;

import java.util.ArrayList;
import java.util.Random;

public class Library {


    public static void main (String []args){

        System.out.println(roll(4));

    }
public static ArrayList  roll(int num){
    Random dice = new Random();
   ArrayList<Integer> arr =new ArrayList<>();

    for (int index=0;index<num ;index++){
        int prop = dice.nextInt(6) +1;
        arr.add(prop);

    }
    return arr;
}

public  boolean containsDuplicates(int[]arr){
     for (int index=0;index<arr.length;index++){
         int num=arr[index];
         for (int index2=0;index2<arr.length;index2++){
            if (arr[index2]==num && index!=index2){
                return true;
            }
         }
     }
        return false;
}

public  double CalculatingAverages(int[]arr){
        double sum =0;
        for (int index=0;index<arr.length;index++){
            sum+=arr[index];
        }
        return sum/ arr.length;
}

public  int[] ArraysOfArrays(int[][]arr){
        double lowAvg=CalculatingAverages(arr[0]);;
        int indexArr=0;
       for (int index =0;index< arr.length;index++){
            double b = CalculatingAverages(arr[index]);
            if (b<lowAvg){
                lowAvg=b;
               indexArr=index;
            }

       }

        return arr[indexArr];
}

// for (int index =0;index<arr.length;index++){
//        for (int index2=0;index2< arr[index].length;index2++){
//            sum+=arr[index][index2];
//            count++;
//        }

}
