/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    @Test
    void instance(){
        Restaurant mac = new Restaurant("MAC");
        mac.toString();
       assertEquals(0.0,mac.getStar());

    }
    @Test
    void AddReview(){
        Restaurant mac = new Restaurant("MAC");
        mac.addReview("this is expensive resturant","Moahmmed",4);
        mac.addReview("this is expensive resturant","Moahmmed",3.5f);
        assertEquals(3.75,mac.getStar());

    }

    @Test
    void instanceOf(){
        Restaurant mac = new Restaurant("MAC");
        if (mac instanceof Restaurant){
            mac.toString();
        }
    }
    @Test
    void  Review(){
        Review review = new Review("Amazing resturant","Saleem",5);
        review.toString();
    }

    @Test
    void MultiReview(){
        Restaurant mac = new Restaurant("MAC");
        Restaurant pizzaHut = new Restaurant("pizza hut");
        mac.addReview("Burger resturant","ahmad",5);
        mac.addReview("good resturant","sameer", 3.50f);
        pizzaHut.addReview("good pizaa","khalil",4);
        pizzaHut.addReview("good pizaa","khalil",2);
        assertEquals(4.25,mac.getStar());
        assertEquals(3,pizzaHut.getStar());
    }
    @Test
    void updateStars (){
        Restaurant ShawrmaSAGE = new Restaurant("ShawrmaSAGE");

        ShawrmaSAGE.addReview("BEST resturant","ahmad",5);
        ShawrmaSAGE.addReview("good SHAWRMA","sameer", 2);
        assertEquals(3.5,ShawrmaSAGE.getStar());
        ShawrmaSAGE.updateStars(4,2);
        assertEquals(4.5,ShawrmaSAGE.getStar());
    }
}
