/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App app =new App();
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void test1(){
        HashSet result = new HashSet<>();
        HashSet result1 = new HashSet<>();

        String[]resultAc= new  String[6];
        resultAc[0]="Never saw temperature: 63";
        resultAc[1]="Low :51";
        resultAc[2]="High :72";
        resultAc[3]="Never saw temperature: 69";
        resultAc[4]="Never saw temperature: 67";
        resultAc[5]="Never saw temperature: 68";

result1.addAll(Arrays.asList(resultAc));

        int[][] testarr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        result.addAll(app.AnalyzingWeatherData(testarr));
        assertEquals(result1,result);
    }
    @Test
    void test2(){
        List<String> votes = new ArrayList<>();
        votes.add("mohammed");
        votes.add("mohammed");
        votes.add("mohammed");
        votes.add("mohammed");
        votes.add("mohammed");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String expected = "mohammed" +"  received the most votes!";

        String result = app.tally(votes);

        assertEquals(expected,result);



    }



}
